dependencies {
	implementation project(':core')

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	testImplementation 'org.springframework.security:spring-security-test'
}
